version: '3.8'
services:
  frontend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - VITE_WEBSOCKET_URL=ws://websocket:8080
      - NODE_ENV=production
    depends_on:
      - websocket

  websocket:
    build: 
      context: .
      dockerfile: docker/Dockerfile.websocket
    ports:
      - "8080:8080"
    environment:
      - DEBUG=y*
      - NODE_ENV=production

  # Optional: Add Nginx as reverse proxy if needed
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./docker/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - websocket
